# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mini_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_server_window(object):
    def setupUi(self, new_server_window):
        new_server_window.setObjectName("new_server_window")
        new_server_window.resize(394, 231)
        new_server_window.setMinimumSize(QtCore.QSize(394, 231))
        new_server_window.setMaximumSize(QtCore.QSize(394, 231))
        self.Server_Name = QtWidgets.QLineEdit(new_server_window)
        self.Server_Name.setGeometry(QtCore.QRect(110, 30, 241, 27))
        self.Server_Name.setObjectName("Server_Name")
        self.URL = QtWidgets.QLineEdit(new_server_window)
        self.URL.setGeometry(QtCore.QRect(110, 80, 241, 27))
        self.URL.setObjectName("URL")
        self.port = QtWidgets.QLineEdit(new_server_window)
        self.port.setGeometry(QtCore.QRect(110, 130, 241, 27))
        self.port.setObjectName("port")
        self.label = QtWidgets.QLabel(new_server_window)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(new_server_window)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 91, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(new_server_window)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 91, 17))
        self.label_3.setObjectName("label_3")
        self.create_server = QtWidgets.QPushButton(new_server_window)
        self.create_server.setGeometry(QtCore.QRect(170, 200, 97, 26))
        self.create_server.setObjectName("create_server")
        self.close = QtWidgets.QPushButton(new_server_window)
        self.close.setGeometry(QtCore.QRect(280, 200, 97, 26))
        self.close.setObjectName("close")
        self.kiss_decoder_enable = QtWidgets.QCheckBox(new_server_window)
        self.kiss_decoder_enable.setGeometry(QtCore.QRect(160, 170, 191, 22))
        self.kiss_decoder_enable.setObjectName("kiss_decoder_enable")

        self.retranslateUi(new_server_window)
        QtCore.QMetaObject.connectSlotsByName(new_server_window)

    def retranslateUi(self, new_server_window):
        _translate = QtCore.QCoreApplication.translate
        new_server_window.setWindowTitle(_translate("new_server_window", "New Server"))
        self.label.setText(_translate("new_server_window", "Server name"))
        self.label_2.setText(_translate("new_server_window", "Server URL"))
        self.label_3.setText(_translate("new_server_window", "Server Port"))
        self.create_server.setText(_translate("new_server_window", "OK"))
        self.close.setText(_translate("new_server_window", "Cancel"))
        self.kiss_decoder_enable.setText(_translate("new_server_window", "Kiss Decoder Enable"))
